platform :ios, '10.0'

target '___PROJECTNAME___' do
  use_frameworks!
  inhibit_all_warnings!

  # Pods for ___PROJECTNAME___
  pod 'Moya'
  pod 'Alamofire'
  pod 'PromisesSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Swinject'
  pod 'SwiftyBeaver'
  pod 'SwiftKeychainWrapper'
  pod 'IGListKit'
  pod 'SVProgressHUD'
  pod 'PinLayout'
  pod 'FontAwesome.swift'

  target '___PROJECTNAME___Tests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
    pod 'OHHTTPStubs'
  end

end
